
#line 3 "lex.yy_res_.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer yy_res__create_buffer
#define yy_delete_buffer yy_res__delete_buffer
#define yy_flex_debug yy_res__flex_debug
#define yy_init_buffer yy_res__init_buffer
#define yy_flush_buffer yy_res__flush_buffer
#define yy_load_buffer_state yy_res__load_buffer_state
#define yy_switch_to_buffer yy_res__switch_to_buffer
#define yyin yy_res_in
#define yyleng yy_res_leng
#define yylex yy_res_lex
#define yylineno yy_res_lineno
#define yyout yy_res_out
#define yyrestart yy_res_restart
#define yytext yy_res_text
#define yywrap yy_res_wrap
#define yyalloc yy_res_alloc
#define yyrealloc yy_res_realloc
#define yyfree yy_res_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yy_res_restart(yy_res_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yy_res_leng;

extern FILE *yy_res_in, *yy_res_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yy_res_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yy_res_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yy_res_restart()), so that the user can continue scanning by
	 * just pointing yy_res_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yy_res_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yy_res_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yy_res_wrap()'s to do buffer switches
 * instead of setting up a fresh yy_res_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yy_res_restart (FILE *input_file  );
void yy_res__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_res__create_buffer (FILE *file,int size  );
void yy_res__delete_buffer (YY_BUFFER_STATE b  );
void yy_res__flush_buffer (YY_BUFFER_STATE b  );
void yy_res_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void yy_res_pop_buffer_state (void );

static void yy_res_ensure_buffer_stack (void );
static void yy_res__load_buffer_state (void );
static void yy_res__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_res__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_res__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_res__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_res__scan_bytes (yyconst char *bytes,int len  );

void *yy_res_alloc (yy_size_t  );
void *yy_res_realloc (void *,yy_size_t  );
void yy_res_free (void *  );

#define yy_new_buffer yy_res__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yy_res_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_res__create_buffer(yy_res_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yy_res_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_res__create_buffer(yy_res_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yy_res_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yy_res_in = (FILE *) 0, *yy_res_out = (FILE *) 0;

typedef int yy_state_type;

extern int yy_res_lineno;

int yy_res_lineno = 1;

extern char *yy_res_text;
#define yytext_ptr yy_res_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yy_res_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yy_res_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 15
#define YY_END_OF_BUFFER 16
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[105] =
    {   0,
        0,    0,    0,    0,   16,   14,    9,   10,   12,   14,
       14,   14,   14,    9,   14,   14,   14,   15,    9,    8,
        9,   12,    0,    4,   11,    4,    9,    0,    4,    4,
        4,    8,    8,    8,    5,    4,    0,    4,    4,    4,
        8,    0,    4,    0,    4,    4,    4,    8,    0,    4,
        0,    0,    4,    4,    8,    5,    4,    0,    0,    4,
        1,    8,    4,    0,    0,    4,    8,    0,    0,    0,
        0,    8,    0,    0,    0,    0,    8,    3,    0,    0,
        0,   13,    8,    0,    0,    7,    0,    0,    0,    0,
        6,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    6,    2,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    1,    1,    1,    8,
        9,    1,    1,    1,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,    1,
        1,    1,    1,    1,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,   14,    1,    1,   13,    1,   15,   13,   16,   17,

       18,   13,   19,   13,   20,   13,   13,   21,   13,   22,
       23,   24,   13,   25,   26,   27,   28,   13,   13,   13,
       13,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[29] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[116] =
    {   0,
        0,   27,   30,   33,  172,  173,   36,  173,    0,    0,
        0,  168,  152,   37,  141,  146,  152,  173,   41,   42,
       46,    0,    0,    0,  173,  142,   47,  141,  137,  147,
      137,    0,   51,  139,  149,  141,  141,  134,  135,  136,
      137,    0,  131,  137,  141,  122,  131,  144,    0,  130,
      119,  117,  127,  116,  116,  130,  114,  121,  114,  119,
        0,  120,  131,  130,  116,   54,  107,  108,  104,  114,
       57,  108,  105,  110,   98,  119,   99,  173,   97,  103,
      115,  173,   89,   95,   92,    0,   71,   58,   57,   68,
       62,   43,   69,   70,   48,   74,    0,   45,   77,   30,

       78,  173,  173,  173,   87,   92,   47,   94,   99,  101,
       25,  103,  108,  112,  114
    } ;

static yyconst flex_int16_t yy_def[116] =
    {   0,
      104,    1,  105,  105,  104,  104,  104,  104,  106,  107,
      108,  104,  108,  104,  108,  108,  108,  104,  104,  109,
      104,  106,  110,  108,  104,  108,  104,  104,  108,  108,
      108,  109,  109,  109,  110,  108,  104,  108,  108,  108,
      109,  111,  108,  104,  108,  108,  108,  109,  112,  108,
      104,  104,  108,  108,  109,  112,  108,  104,  104,  108,
      108,  109,  108,  104,  104,  108,  109,  104,  104,  104,
      104,  109,  104,  104,  104,  113,  109,  104,  104,  104,
      113,  104,  109,  104,  104,  109,  104,  104,  104,  104,
      104,  104,  104,  114,  104,  114,  115,  104,  115,  104,

      104,  104,  104,    0,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104
    } ;

static yyconst flex_int16_t yy_nxt[202] =
    {   0,
        6,    7,    8,    7,    6,    9,   10,    6,    6,    6,
        6,    6,   11,   12,   11,   11,   13,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   14,   49,
       14,   19,    8,   19,   20,    8,   20,   21,   27,   21,
       27,   15,   21,   33,   21,   33,   16,   21,   27,   21,
       27,   23,   33,   17,   33,   71,  103,   71,   71,   34,
       71,   76,  100,   93,   28,   93,   98,   95,   34,   94,
       93,   96,   93,   96,   28,   96,   94,   96,  101,  101,
      101,  101,   92,   91,   90,  102,  102,   18,   18,   18,
       18,   18,   22,   22,   89,   22,   22,   24,   24,   32,

       32,   88,   32,   32,   35,   35,   56,   56,   81,   81,
       81,   81,   81,   97,   87,   86,   97,   99,   99,   82,
       85,   84,   83,   82,   80,   79,   78,   77,   75,   74,
       73,   72,   70,   69,   68,   67,   66,   65,   64,   63,
       42,   62,   61,   60,   59,   58,   57,   55,   54,   53,
       52,   51,   50,   48,   47,   46,   45,   44,   43,   42,
       41,   40,   39,   38,   37,   36,   31,   30,   29,   26,
       25,  104,    5,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      104
    } ;

static yyconst flex_int16_t yy_chk[202] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,  111,
        2,    3,    3,    3,    4,    4,    4,    7,   14,    7,
       14,    2,   19,   20,   19,   20,    2,   21,   27,   21,
       27,  107,   33,    2,   33,   66,  100,   66,   71,   20,
       71,   71,   98,   91,   14,   91,   95,   92,   33,   91,
       93,   94,   93,   94,   27,   96,   93,   96,   99,  101,
       99,  101,   90,   89,   88,   99,  101,  105,  105,  105,
      105,  105,  106,  106,   87,  106,  106,  108,  108,  109,

      109,   85,  109,  109,  110,  110,  112,  112,  113,  113,
      113,  113,  113,  114,   84,   83,  114,  115,  115,   81,
       80,   79,   77,   76,   75,   74,   73,   72,   70,   69,
       68,   67,   65,   64,   63,   62,   60,   59,   58,   57,
       56,   55,   54,   53,   52,   51,   50,   48,   47,   46,
       45,   44,   43,   41,   40,   39,   38,   37,   36,   35,
       34,   31,   30,   29,   28,   26,   17,   16,   15,   13,
       12,    5,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      104
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_res__flex_debug;
int yy_res__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yy_res_text;
#line 1 "resolver/scanner.l"
#line 2 "resolver/scanner.l"

#define YY_DECL int yy_res_lex(yy_res_parser_t *parser)

#include <stdio.h>
#include <limits.h>

#include <murphy/common/mm.h>
#include <murphy/common/log.h>

#include "murphy/resolver/resolver.h"
#include "murphy/resolver/scanner.h"
#include "murphy/resolver/token.h"
#include "murphy/resolver/parser-api.h"
#include "murphy/resolver/parser.h"

#define YY_NO_INPUT

#define yy_res_create_buffer    yy_res__create_buffer
#define yy_res_delete_buffer    yy_res__delete_buffer
#define yy_res_switch_to_buffer yy_res__switch_to_buffer
#define yy_res_scan_buffer      yy_res__scan_buffer


/*
 * lexical analyser input sources
 *
 * We support an include mechanism similar to the #include directive
 * of the C-preprocessor. When one input file includes another, this
 * is treated as if the latter file was verbatim copied in place of
 * the include directive in the former file.
 *
 * The include mechanism is (almost) entirely implemented in the lexical
 * analyser and is transparet to/hidden from the parser. The functions
 * below and the macro CHECK_EOF take care of inclusion.
 *
 * Note that currently there is no any attempt to check for and prevent
 * circular inclusion loops...
 */

int scanner_push_file(yy_res_parser_t *parser, const char *file)
{
    yy_res_input_t *in;
    char            buf[PATH_MAX], *base;
    const char     *path;
    int             len;
    FILE           *fp;

    if (*file != '/' && parser->in != NULL) {
        base = strrchr(parser->in->name, '/');
        if (base != NULL) {
            len = base - parser->in->name;
            snprintf(buf, sizeof(buf), "%*.*s/%s",
                     len, len, parser->in->name, file);
            path = buf;
        }
        else
            path = file;
    }
    else
        path = file;

    fp = fopen(path, "r");

    if (fp != NULL) {
        in = mrp_allocz(sizeof(*in));

        if (in != NULL) {
            in->fp    = fp;
            in->name  = mrp_strdup(path);
            in->line  = 1;
            in->yybuf = yy_res_create_buffer(in->fp, YY_BUF_SIZE);
            in->prev  = parser->in;

            yy_res_switch_to_buffer(in->yybuf);

            parser->in = in;

            return TRUE;
        }
        else
            fclose(fp);
    }
    else
        mrp_log_error("Failed to open input file '%s' ('%s', error: %s).",
                      file, path, strerror(errno));

    return FALSE;
}


void scanner_free_input(yy_res_input_t *in)
{
    if (in != NULL) {
        if (in->fp != NULL)
            fclose(in->fp);
        mrp_free(in->name);
        yy_res_delete_buffer(in->yybuf);

        mrp_free(in);
    }
}


int scanner_pop_input(yy_res_parser_t *parser)
{
    yy_res_input_t *in, *prev;

    if (parser->in != NULL) {
        in   = parser->in;
        prev = in->prev;

        in->prev     = parser->done;
        parser->done = in;

        parser->in = prev;
        if (prev != NULL) {
            yy_res_switch_to_buffer(prev->yybuf);

            return TRUE;                 /* more input to process */
        }
    }

    return FALSE;                        /* no more input */
}


/*
 * ringbuffer of tokens
 *
 * To simplify the lifecycle management of tokens passed between the
 * lexical analyser and the parser we collect them into a ring buffer
 * instead of dynamic allocation. This simplifies both the lexical
 * analyser and the parser and allows us to have sane owner allocates /
 * owner frees allocation semantics. The price we pay for this is that
 * the ring buffer must be big enough to accomodate all the unprocessed
 * tokens between bison rule reductions.
 */

static char *save_token(yy_res_parser_t *parser, char *str, size_t size)
{
    char *token;

    if (!size)
        size = strlen(str);

    if (parser->offs + size + 1 >= YY_RES_RINGBUF_SIZE)
        parser->offs = 0;

    token = parser->ringbuf + parser->offs;
    parser->offs += size + 1;

#ifdef __MURPHY_RESOLVER_CHECK_RINGBUF__
    if (*token != '\0') {
        mrp_log_error("Token ring buffer overflow in resolver lexical "
                      "analyser.");
        exit(1);
    }
#endif

    strncpy(token, str, size);
    token[size] = '\0';

    yy_res_lval.any.token  = token;
    yy_res_lval.any.source = parser->in->name;
    yy_res_lval.any.line   = parser->in->line;
    yy_res_lval.any.size   = size;

    return token;
}


/*
 * string token types (must include all token types passed via STRING_TOKEN)
 */

typedef enum {
    STRING_TYPE_IDENT,
    STRING_TYPE_FACT,
    STRING_TYPE_SCRIPT_LINE,
} string_type_t;


#define KEYWORD_TOKEN(tkn) do {                         \
        save_token(parser, yy_res_text, yy_res_leng);   \
                                                        \
        mrp_debug("KEY_%s", #tkn);                      \
                                                        \
        return KEY_##tkn;                               \
    } while (0)

#define KEYWORD_TOKENV(tkn, val, size) do {             \
        size_t  _size;                                  \
        char   *_t;                                     \
                                                        \
        _size = size ? size : strlen(val);              \
        _t    = save_token(parser, val, _size);         \
        yy_res_lval.string.value = _t;                  \
                                                        \
        mrp_debug("KEY_%s ('%s')", #tkn, val);          \
                                                        \
        return KEY_##tkn;                               \
    } while (0)


#define STRING_TOKEN(tkn) do {                          \
        char *_t, *_v;                                  \
        int   _l;                                       \
                                                        \
        switch (STRING_TYPE_##tkn) {                    \
        case STRING_TYPE_FACT:                          \
            _v = yy_res_text;                           \
            _l = yy_res_leng;                           \
            break;                                      \
        default:                                        \
            _v = yy_res_text;                           \
            _l = yy_res_leng;                           \
        }                                               \
                                                        \
        _t = save_token(parser, _v, _l);                \
        yy_res_lval.string.value = _t;                  \
                                                        \
        mrp_debug("TKN_%s ('%s')", #tkn, _t);           \
                                                        \
        return TKN_##tkn;                               \
    } while (0)


#define IGNORE_TOKEN(tkn) do {                          \
        mrp_debug("ignore %s ('%s')", #tkn,             \
                  yy_res_text);                         \
    } while (0)


#define INCLUDE_FILE() do {                             \
        char *_p;                                       \
        int   _l;                                       \
                                                        \
        _p = strchr(yy_res_text, '"');                  \
        if (_p != NULL) {                               \
            _p++;                                       \
            _l = yy_res_leng - (_p - yy_res_text);      \
            _p = save_token(parser, _p, _l - 1);        \
                                                        \
            mrp_debug("including file '%s'...", _p);    \
                                                        \
            if (!scanner_push_file(parser, _p))         \
                return TKN_LEX_ERROR;                   \
        }                                               \
    } while (0)

#define CHECK_EOF() do {                                \
        if (!scanner_pop_input(parser))                 \
            yyterminate();                              \
    } while (0)


#line 807 "lex.yy_res_.c"

#define INITIAL 0
#define SCRIPT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yy_res_lex_destroy (void );

int yy_res_get_debug (void );

void yy_res_set_debug (int debug_flag  );

YY_EXTRA_TYPE yy_res_get_extra (void );

void yy_res_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *yy_res_get_in (void );

void yy_res_set_in  (FILE * in_str  );

FILE *yy_res_get_out (void );

void yy_res_set_out  (FILE * out_str  );

int yy_res_get_leng (void );

char *yy_res_get_text (void );

int yy_res_get_lineno (void );

void yy_res_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yy_res_wrap (void );
#else
extern int yy_res_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yy_res_text, yy_res_leng, 1, yy_res_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yy_res_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yy_res_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yy_res_in))==0 && ferror(yy_res_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yy_res_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yy_res_lex (void);

#define YY_DECL int yy_res_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yy_res_text and yy_res_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yy_res_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yy_res_text[yy_res_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 285 "resolver/scanner.l"


#line 994 "lex.yy_res_.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yy_res_in )
			yy_res_in = stdin;

		if ( ! yy_res_out )
			yy_res_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yy_res_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_res__create_buffer(yy_res_in,YY_BUF_SIZE );
		}

		yy_res__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yy_res_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 105 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 104 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 287 "resolver/scanner.l"
{ KEYWORD_TOKEN(TARGET);                         }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 288 "resolver/scanner.l"
{ KEYWORD_TOKEN(AUTOUPDATE);                     }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 289 "resolver/scanner.l"
{ KEYWORD_TOKEN(DEPENDS_ON);                     }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 290 "resolver/scanner.l"
{ STRING_TOKEN(IDENT);                           }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 291 "resolver/scanner.l"
{ STRING_TOKEN(FACT);                            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 293 "resolver/scanner.l"
{
                        char   *type, *end, *p;
                        size_t  len;

                        BEGIN(SCRIPT);

                        type = strchr(yy_res_text, '(');

                        if (type != NULL) {
                            end = strchr(type, ')');
                            len = end - type - 1;
                            p   = type + 1;
                            while (*p == ' ' || *p == '\t')
                                p++, len--;
                            while (len > 0 &&
                                   (p[len-1] == ' ' || p[len-1] == '\t'))
                                len--;

                            KEYWORD_TOKENV(UPDATE_SCRIPT, p, len);
                        }
                        else
                            KEYWORD_TOKENV(UPDATE_SCRIPT, "simple", 0);
                      }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 316 "resolver/scanner.l"
{ BEGIN(INITIAL); KEYWORD_TOKEN(END_SCRIPT);     }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 317 "resolver/scanner.l"
{ STRING_TOKEN(SCRIPT_LINE);                     }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 319 "resolver/scanner.l"
{ /*IGNORE_TOKEN(WS);*/                          }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 320 "resolver/scanner.l"
{ parser->in->line++; /*IGNORE_TOKEN(EOL);*/     }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 321 "resolver/scanner.l"
{ parser->in->line++; /*IGNORE_TOKEN(EOL);*/     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 322 "resolver/scanner.l"
{ parser->in->line++; /*IGNORE_TOKEN(COMMENT);*/ }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 323 "resolver/scanner.l"
{ INCLUDE_FILE();                                }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SCRIPT):
#line 324 "resolver/scanner.l"
{ CHECK_EOF();                                   }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 326 "resolver/scanner.l"
{ mrp_log_error("Unhandled token '%s'",
                                      yy_res_text);                    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 328 "resolver/scanner.l"
ECHO;
	YY_BREAK
#line 1180 "lex.yy_res_.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yy_res_in at a new source and called
			 * yy_res_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yy_res_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yy_res_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yy_res_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yy_res_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_res_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yy_res_restart(yy_res_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yy_res_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 105 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 105 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 104);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yy_res_restart(yy_res_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yy_res_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yy_res_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yy_res_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yy_res_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_res__create_buffer(yy_res_in,YY_BUF_SIZE );
	}

	yy_res__init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_res__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_res__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yy_res_pop_buffer_state();
	 *		yy_res_push_buffer_state(new_buffer);
     */
	yy_res_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_res__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yy_res_wrap()) processing, but the only time this flag
	 * is looked at is after yy_res_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_res__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yy_res_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_res__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yy_res_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_res__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_res_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_res__create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_res__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_res__create_buffer()
 * 
 */
    void yy_res__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_res_free((void *) b->yy_ch_buf  );

	yy_res_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yy_res_restart() or at EOF.
 */
    static void yy_res__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_res__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_res__init_buffer was _probably_
     * called from yy_res_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_res__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_res__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yy_res_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yy_res_ensure_buffer_stack();

	/* This block is copied from yy_res__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_res__switch_to_buffer. */
	yy_res__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yy_res_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_res__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_res__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yy_res_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yy_res_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yy_res_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yy_res_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yy_res_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_res__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_res_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_res__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_res__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yy_res_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_res__scan_bytes() instead.
 */
YY_BUFFER_STATE yy_res__scan_string (yyconst char * yystr )
{
    
	return yy_res__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yy_res_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_res__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yy_res_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_res__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_res__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_res__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yy_res_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yy_res_text[yy_res_leng] = (yy_hold_char); \
		(yy_c_buf_p) = yy_res_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yy_res_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yy_res_get_lineno  (void)
{
        
    return yy_res_lineno;
}

/** Get the input stream.
 * 
 */
FILE *yy_res_get_in  (void)
{
        return yy_res_in;
}

/** Get the output stream.
 * 
 */
FILE *yy_res_get_out  (void)
{
        return yy_res_out;
}

/** Get the length of the current token.
 * 
 */
int yy_res_get_leng  (void)
{
        return yy_res_leng;
}

/** Get the current token.
 * 
 */

char *yy_res_get_text  (void)
{
        return yy_res_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yy_res_set_lineno (int  line_number )
{
    
    yy_res_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_res__switch_to_buffer
 */
void yy_res_set_in (FILE *  in_str )
{
        yy_res_in = in_str ;
}

void yy_res_set_out (FILE *  out_str )
{
        yy_res_out = out_str ;
}

int yy_res_get_debug  (void)
{
        return yy_res__flex_debug;
}

void yy_res_set_debug (int  bdebug )
{
        yy_res__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yy_res_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yy_res_in = stdin;
    yy_res_out = stdout;
#else
    yy_res_in = (FILE *) 0;
    yy_res_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yy_res_lex_init()
     */
    return 0;
}

/* yy_res_lex_destroy is for both reentrant and non-reentrant scanners. */
int yy_res_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_res__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yy_res_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	yy_res_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yy_res_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yy_res_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yy_res_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yy_res_free (void * ptr )
{
	free( (char *) ptr );	/* see yy_res_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 328 "resolver/scanner.l"
